### ISSUE TITLE
Import error on Windows

### ISSUE THREAD

**Issue by carlpett** [saltstack/pytest-salt#18]
It seems that despite the warning in the readme (ATTENTION: THIS IS NOT STILL NOT READY TO BE USED), this is actually used in salt now. I cannot run unit tests on my Windows machine due to an import error [here](https://github.com/saltstack/pytest-salt/blob/master/pytestsalt/fixtures/config.py#L18). `pwd` is not available on Windows. When using the module you are already [handling Windows separately](https://github.com/saltstack/pytest-salt/blob/master/pytestsalt/fixtures/config.py#L183), but the import fails.

Locally I've now moved the import to an else-clause from the win32api import, not sure if that is ideal, however.

**Comment by s0undt3ch** [comment]
Thank You for your valuable input.

I've updated the README to reflect the current status of the project. And fixed the import issue.
