### ISSUE TITLE
tag a release

### ISSUE THREAD

**Issue by chutz** [saltstack/pytest-salt#26]
Please tag a release of this, so it can be more easily packaged as a dependency of the main salt package to allow tests to be run

**Comment by skizunov** [comment]
@s0undt3ch : I would also like this to be tagged so that it may easily be packaged. Are there any plans to tag this for use with salt 2017.7.1?

**Comment by s0undt3ch** [comment]
Tagged [v2017.8.23](https://github.com/saltstack/pytest-salt/releases/tag/v2017.8.23). Closing.
