### ISSUE TITLE
Last release sources are missing on pypi

### ISSUE THREAD

**Issue by baby-gnu** [saltstack/pytest-salt#35]
Hello.

I'm looking at the packaging of the latest release for Debian and found that there is no source on the [last pypi published release](https://pypi.org/project/pytest-salt/2018.9.18/).

The problem is that the Debian tools track only the sources and so don't see the good last release: https://tracker.debian.org/pkg/pytest-salt

Please, could you upload the sources on pypi in addition of the wheel?

Regards.

**Comment by s0undt3ch** [comment]
I missed that step when release, sorry.
The source tarbal is now also uploaded.

**Comment by baby-gnu** [comment]
Thanks a lot.
