### ISSUE TITLE
Error when loading pytestsalt.utils.ipc because of a missing except

### ISSUE THREAD

**Issue by baby-gnu** [saltstack/pytest-salt#36]
Hello.

I'm trying to package that module for Debian but pylint3 fails with the following:

```
No config file found, using default configuration
************* Module pytestsalt.utils.ipc
E: 84, 0: unexpected unindent (<string>, line 84) (syntax-error)
```

This is because of a missing `except` in `IPCServer.handle_stream`.

**Comment by s0undt3ch** [comment]
Dam. That shouldn't have been packaged. I'll do another release and upload I tomorrow.

**Comment by s0undt3ch** [comment]
This should now be fixed

**Comment by baby-gnu** [comment]
Great thanks, do you plan to make a release soon or should I backport the patch in my packaging?
